flows:
  - uid: 87e5512b-cbff-4e3f-a679-69b189b8e03f
    title: ارتباط در زیرشبکه
    address: 127.0.0.1
    port: 6969
    type: udp
    direction: 3
  - uid: a0ab73c5-f5d3-4830-bcd3-58d1141b4e35
    title: ارتباط رادیویی
    address: amqp://rabbitmq-server-address
    port: 0
    type: rabbit
    direction: 1
    recvQueue: IncomingMsgQueue
sensors:
  - title: رادار!
    addr: ""
    port: 11111
    uid: 71c9dda0-ef45-49e1-84d3-864185429802
    type: Radar
    interval: 5
  - title: a
    addr: ""
    port: 1234
    uid: b9bae8a1-3ba2-483a-b3ff-0f09c0fcc038
    type: AIS
    interval: 5
me:
  callsign: نود ششم شبکه
  lat: 35.777088
  lon: 51.471548
  zoom: 12
  type: a-f-G-I-B
  team: Blue
  role: HQ
  platform: GoATAK_client
  version: unknown
  urn: 6
  ip: 192.168.11.6
  uid: NODE6
  os: ""
  interval: 30
  device: ""
web_port: 8080
debug: false
no_web: false
file: ""
server_address: 127.0.0.1:8087:tcp
gpsd: gpsd:2947
dns_service.url: http://dns.api
gps_port: ""
map_server: 127.0.0.1:8000
db_path: config/goatak.db
tracking:
  enabled: true
  default_trail_length: 0
  default_update_interval: 0
  default_trail_color: ""
  default_trail_width: 0
